//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fonlow.VA.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fonlow.VA.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Charts.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Distance (Foot).
        /// </summary>
        public static string ArmReachDistanceFootLabel {
            get {
                return ResourceManager.GetString("ArmReachDistanceFootLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Distance (Meter).
        /// </summary>
        public static string ArmReachDistanceMeterLabel {
            get {
                return ResourceManager.GetString("ArmReachDistanceMeterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tumbling E.
        /// </summary>
        public static string ChartE {
            get {
                return ResourceManager.GetString("ChartE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landolt C.
        /// </summary>
        public static string ChartLandoltC {
            get {
                return ResourceManager.GetString("ChartLandoltC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snellen.
        /// </summary>
        public static string ChartSnellen {
            get {
                return ResourceManager.GetString("ChartSnellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        public static string DecimalLabel {
            get {
                return ResourceManager.GetString("DecimalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Information.
        /// </summary>
        public static string DeviceInformation {
            get {
                return ResourceManager.GetString("DeviceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Details.
        /// </summary>
        public static string ExportAllToHtml {
            get {
                return ResourceManager.GetString("ExportAllToHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Trend.
        /// </summary>
        public static string ExportAllToLineGraphHtml {
            get {
                return ResourceManager.GetString("ExportAllToLineGraphHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://visualacuity.info/TumblingEChartPrivacyPolicy.
        /// </summary>
        public static string PrivacyPolicyE {
            get {
                return ResourceManager.GetString("PrivacyPolicyE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicyLabel {
            get {
                return ResourceManager.GetString("PrivacyPolicyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://visualacuity.info/SnellenChartPrivacyPolicy.
        /// </summary>
        public static string PrivacyPolicySnellen {
            get {
                return ResourceManager.GetString("PrivacyPolicySnellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://visualacuity.info/VisualAcuityChartsPrivacyPolicy.
        /// </summary>
        public static string PrivacyPolicyVAC {
            get {
                return ResourceManager.GetString("PrivacyPolicyVAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share All as CSV File.
        /// </summary>
        public static string ShareAllAsCsv {
            get {
                return ResourceManager.GetString("ShareAllAsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share All.
        /// </summary>
        public static string ShareAllAsHtml {
            get {
                return ResourceManager.GetString("ShareAllAsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share All as JSON File.
        /// </summary>
        public static string ShareAllAsJson {
            get {
                return ResourceManager.GetString("ShareAllAsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Trend.
        /// </summary>
        public static string ShareAllAsLineGraphHtml {
            get {
                return ResourceManager.GetString("ShareAllAsLineGraphHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ShareAllAsText {
            get {
                return ResourceManager.GetString("ShareAllAsText", resourceCulture);
            }
        }
    }
}
